import { Inter } from "next/font/google";
import "./globals.css";
import { DashBoard } from "./components/DashBoard";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tasks App",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: '#ba9ffb',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`p-3 w-screen h-dvh flex flex-col lg:flex-row gap-2 ${inter.className} antialiased dark:bg-[#1a1625]`}>
        <aside className="bg-neutral-200 dark:bg-[#46424f] dark:text-white h-14 lg:h-full lg:w-52 rounded-md p-4 order-2 lg:order-1">
          <DashBoard />
        </aside>
        <main className="flex-1 p-2 lg:p-4 order-1 lg:order-2 overflow-y-scroll">
          {children}
        </main>
      </body>
    </html>
  );
}
